/* GENERATED FILE - do not edit by hand.
   Source of truth is content/cases.csv; regenerate with:
     powershell -ExecutionPolicy Bypass -File tools/build-cases.ps1
   Edits made directly here are lost on the next run. */
window.CASE_DATA = {
  en: {
    category: "Concept Project",
    title: "EV Charger",
    summary: "An all-in-one app for EV drivers, pulling station search, reservation and payment into one journey instead of three.",
    coverAlt: "EV Charger app screens showing map, station detail and charging status",
    role: "UX/UI Designer",
    timeline: "2023 — 4 months",
    platform: "Mobile — iOS",
    tools: "Figma, Prototype, Mockup",
    problem1: "Getting to a charger should not be the hard part of driving an electric car.",
    problem2: "",
    process1: "I started by going through the EV charging apps already on the market to find where they broke down, built a picture of who was actually driving these cars, and mapped the journey from opening the app to finishing a charge — trying to take out steps rather than add screens. Wireframes came before any visual work, and the whole thing ended as an interactive prototype with device mockups for presenting it.",
    quote: "Someone opening this may well be driving. Big targets, few words, one decision per screen.",
    solution1: "The flow to pick a station and a connector was cut down until a reservation takes a few taps, and the map and charging dashboard were built around a hierarchy you can read at a glance — because the person reading it is often about to drive, or already driving.",
    caption1: "Onboarding — the app introduced, with a single way in",
    caption2: "Sign in — email and password, or Google",
    caption3: "Home — services and shortcuts, with news beneath",
    results1: "The concept was carried through end to end: every screen in the journey designed, prototyped and mocked up for presentation. Cutting the booking flow down was the point of the exercise — the numbers below are what was produced, not measured use, since this was never put in front of drivers.",
    stat1: "7+",
    stat1Label: "High-fidelity screens",
    stat2: "1",
    stat2Label: "End-to-end user flow",
    stat3: "1",
    stat3Label: "Interactive prototype",
    nextTitle: "JST Group",
    pageTitle: "EV Charger",
    client: "Self-initiated concept project",
    contextText: "A concept project, started in response to how quickly electric vehicles were being adopted here. The aim was to improve the experience of finding and reserving a charging station, covering the journey end to end: an interactive map, station and connector selection, and a live charging status dashboard. Its users are EV drivers.",
    prob1Title: "The Problem",
    prob1Text: "EV charging apps are still immature. The ones that exist tend to be hard to use, carry stale data, and — worst of all — bury station and connector selection in convoluted flows. People give up partway through a booking.",
    prob2Title: "",
    prob2Text: "",
    prob3Title: "",
    prob3Text: "",
    goalTitle: "The Goal",
    goalText: "Remove that friction with a full UI rework — something clean and immediately legible, where a driver can move through the app without thinking about it and finish a reservation quickly.",
    ps1Title: "Research & Analysis",
    ps1Text: "Work through the EV charging apps on the market and find where they fail",
    ps2Title: "User Persona",
    ps2Text: "Build a picture of the EV driver — needs, habits, frustrations",
    ps3Title: "User Flow",
    ps3Text: "Map opening the app through to finishing a charge, in as few steps as it takes",
    ps4Title: "Wireframe",
    ps4Text: "Low-fidelity layouts to test the information architecture before any styling",
    ps5Title: "UI Design",
    ps5Text: "High-fidelity screens against the agreed visual direction",
    ps6Title: "Prototype & Mockup",
    ps6Text: "An interactive prototype plus device mockups for presenting it",
    sol1Title: "Interactive Map",
    sol1Text: "Find nearby stations on a live map rather than through a list you have to interpret.",
    sol2Title: "Station & Connector Selection",
    sol2Text: "Pick the station and the connector type — Type 2, CCS — without leaving the map.",
    sol3Title: "Reservation",
    sol3Text: "Reserve a slot ahead, with the distance and travel time shown alongside it.",
    sol4Title: "Charging Dashboard",
    sol4Text: "Live charging status, readable at a glance while you wait.",
    dec1Title: "Map first",
    dec1Why: "An EV driver wants the nearest station as fast as possible, so the map is the first thing after sign-in rather than something to navigate to.",
    dec2Title: "Blue and white as the primary",
    dec2Why: "Reads as clean energy and modernity without leaning on the obvious green.",
    dec3Title: "Bottom sheet for detail",
    dec3Why: "Station detail opens over the map instead of on a new screen, so the driver never loses the context they were looking at.",
    dec4Title: "Connector type as a badge",
    dec4Why: "Type and power in kW sit on the pin itself — the two facts that decide whether this station is any use to your car.",
    dec5Title: "Availability as colour",
    dec5Why: "Free or occupied, settled before you tap — a decision that should not need a second screen to make.",
    stat4: "6",
    stat4Label: "Device mockups",
    reflect1Title: "Map-based interaction",
    reflect1Text: "Pins, bottom sheets, clustering and search radius behave differently from ordinary screens, and have to be designed as their own thing.",
    reflect2Title: "Reading the market first",
    reflect2Text: "Working through what already exists is how you find the gap worth designing into, rather than guessing at one.",
    reflect3Title: "A concept has to sell itself",
    reflect3Text: "With no client and no users, the mockups and the presentation carry the whole argument — which is its own skill.",
    reflect4Title: "Learning the domain",
    reflect4Text: "Connector standards, charging speeds and pricing models all shape the interface — you cannot design this one from the outside.",
    caption4: "Map — station pins carrying connector type and power",
    caption5: "Booking — distance and travel time before you commit",
    caption6: "Station list — nearby operators, each with type and kW",
    dataStatus: "real"
  },

  th: {
    category: "โปรเจกต์แนวคิด",
    title: "EV Charger",
    summary: "แอปครบวงจรสำหรับผู้ใช้รถไฟฟ้า รวมการค้นหาสถานี การจอง และการจ่ายเงิน ให้อยู่ในเส้นทางเดียว แทนที่จะแยกเป็นสามเรื่อง",
    coverAlt: "หน้าจอแอป EV Charger แสดงแผนที่ รายละเอียดสถานี และสถานะการชาร์จ",
    role: "UX/UI Designer",
    timeline: "2566 — 4 เดือน",
    platform: "มือถือ — iOS",
    tools: "Figma, Prototype, Mockup",
    problem1: "การไปให้ถึงที่ชาร์จ ไม่ควรเป็นส่วนที่ยากที่สุดของการขับรถไฟฟ้า",
    problem2: "",
    process1: "ผมเริ่มจากไล่ดูแอปชาร์จรถไฟฟ้าที่มีอยู่ในตลาดว่าพังตรงไหน สร้างภาพว่าคนที่ขับรถแบบนี้จริง ๆ เป็นใคร แล้ววางเส้นทางตั้งแต่เปิดแอปจนชาร์จเสร็จ โดยพยายามตัดขั้นตอนออก ไม่ใช่เพิ่มหน้าจอ ทำ Wireframe ก่อนเริ่มงานภาพ และจบด้วย Interactive Prototype พร้อม Mockup สำหรับนำเสนอ",
    quote: "คนที่เปิดแอปนี้อาจกำลังขับรถอยู่ ปุ่มต้องใหญ่ ตัวหนังสือต้องน้อย และหนึ่งหน้าจอต่อหนึ่งการตัดสินใจ",
    solution1: "ตัดขั้นตอนการเลือกสถานีและหัวชาร์จลงจนการจองเหลือไม่กี่แตะ ส่วนแผนที่และหน้าสถานะการชาร์จสร้างบนลำดับชั้นที่กวาดตาอ่านได้ในครั้งเดียว เพราะคนที่อ่านมักกำลังจะขับรถ หรือขับอยู่แล้ว",
    caption1: "Onboarding — แนะนำแอป พร้อมทางเข้าเดียว",
    caption2: "เข้าสู่ระบบ — อีเมลและรหัสผ่าน หรือผ่าน Google",
    caption3: "หน้าหลัก — บริการและทางลัด พร้อมข่าวสารด้านล่าง",
    results1: "แนวคิดนี้ถูกทำจนจบเส้นทาง ออกแบบครบทุกหน้าจอ ทำ Prototype และ Mockup สำหรับนำเสนอ การตัดขั้นตอนการจองลงคือโจทย์หลักของงานนี้ ตัวเลขด้านล่างคือสิ่งที่ผลิตออกมา ไม่ใช่ผลการใช้งานจริง เพราะงานนี้ยังไม่เคยผ่านมือผู้ขับจริง",
    stat1: "7+",
    stat1Label: "หน้าจอ High-fidelity",
    stat2: "1",
    stat2Label: "User Flow ครบเส้นทาง",
    stat3: "1",
    stat3Label: "Interactive Prototype",
    nextTitle: "JST Group",
    pageTitle: "EV Charger",
    client: "โปรเจกต์แนวคิดที่ริเริ่มเอง",
    contextText: "โปรเจกต์แนวคิดที่เริ่มทำขึ้นเองจากการที่รถยนต์ไฟฟ้าถูกใช้งานเพิ่มขึ้นอย่างรวดเร็ว เป้าหมายคือทำให้ประสบการณ์การค้นหาและจองสถานีชาร์จดีขึ้น ครอบคลุมเส้นทางตั้งแต่ต้นจนจบ ทั้งแผนที่แบบโต้ตอบ การเลือกสถานีและหัวชาร์จ และหน้าแสดงสถานะการชาร์จแบบเรียลไทม์ กลุ่มผู้ใช้คือผู้ขับรถยนต์ไฟฟ้า",
    prob1Title: "โจทย์",
    prob1Text: "แอปสำหรับชาร์จรถไฟฟ้ายังไม่สุกงอม แอปที่มีอยู่มักใช้งานยาก ข้อมูลไม่อัปเดต และที่แย่ที่สุดคือฝังการเลือกสถานีและหัวชาร์จไว้ในขั้นตอนที่ยุ่งยาก ผู้ใช้จึงเลิกกลางคันระหว่างจอง",
    prob2Title: "",
    prob2Text: "",
    prob3Title: "",
    prob3Text: "",
    goalTitle: "เป้าหมาย",
    goalText: "ลดแรงเสียดทานนั้นด้วยการรื้อ UI ใหม่ทั้งหมด ให้สะอาดและอ่านออกทันที ผู้ขับเคลื่อนผ่านแอปได้โดยไม่ต้องคิด และจองให้จบได้เร็ว",
    ps1Title: "ค้นคว้าและวิเคราะห์",
    ps1Text: "ไล่ดูแอปชาร์จรถไฟฟ้าที่มีในตลาด หาจุดที่ใช้งานไม่ได้จริง",
    ps2Title: "สร้าง Persona",
    ps2Text: "สร้างภาพผู้ใช้รถไฟฟ้า ทั้งความต้องการ พฤติกรรม และความหงุดหงิด",
    ps3Title: "วาง User Flow",
    ps3Text: "วางเส้นทางตั้งแต่เปิดแอปจนชาร์จเสร็จ ให้น้อยขั้นที่สุดเท่าที่จำเป็น",
    ps4Title: "Wireframe",
    ps4Text: "ร่างแบบหยาบเพื่อทดสอบโครงสร้างข้อมูล ก่อนลงรายละเอียดงานภาพ",
    ps5Title: "ออกแบบ UI",
    ps5Text: "ออกแบบหน้าจอ High-fidelity ตาม Visual Direction ที่กำหนด",
    ps6Title: "Prototype และ Mockup",
    ps6Text: "Interactive Prototype พร้อม Device Mockup สำหรับนำเสนอ",
    sol1Title: "แผนที่แบบโต้ตอบ",
    sol1Text: "ค้นหาสถานีใกล้เคียงบนแผนที่แบบเรียลไทม์ แทนที่จะเป็นรายการที่ต้องตีความเอง",
    sol2Title: "เลือกสถานีและหัวชาร์จ",
    sol2Text: "เลือกสถานีและประเภทหัวชาร์จ Type 2 หรือ CCS ได้โดยไม่ต้องออกจากแผนที่",
    sol3Title: "การจอง",
    sol3Text: "จองคิวล่วงหน้าได้ พร้อมแสดงระยะทางและเวลาเดินทางไว้ข้าง ๆ",
    sol4Title: "หน้าสถานะการชาร์จ",
    sol4Text: "สถานะการชาร์จแบบเรียลไทม์ อ่านได้ในสายตาเดียวระหว่างรอ",
    dec1Title: "ขึ้นแผนที่เป็นอย่างแรก",
    dec1Why: "ผู้ขับรถไฟฟ้าต้องการหาสถานีที่ใกล้ที่สุดให้เร็วที่สุด แผนที่จึงเป็นสิ่งแรกหลังเข้าสู่ระบบ ไม่ใช่สิ่งที่ต้องกดหา",
    dec2Title: "ใช้ฟ้า-ขาวเป็นสีหลัก",
    dec2Why: "สื่อถึงพลังงานสะอาดและความทันสมัย โดยไม่ต้องพึ่งสีเขียวที่ตรงตัวเกินไป",
    dec3Title: "ใช้ Bottom Sheet แสดงรายละเอียด",
    dec3Why: "รายละเอียดสถานีเปิดทับบนแผนที่แทนที่จะเป็นหน้าใหม่ ผู้ขับจึงไม่หลุดจากบริบทที่กำลังดูอยู่",
    dec4Title: "แสดงหัวชาร์จเป็น Badge",
    dec4Why: "ประเภทหัวชาร์จและกำลังไฟเป็น kW อยู่บนหมุดเลย สองอย่างนี้คือสิ่งที่ตัดสินว่าสถานีนี้ใช้กับรถคุณได้หรือไม่",
    dec5Title: "บอกสถานะว่างด้วยสี",
    dec5Why: "ว่างหรือไม่ว่าง รู้ได้ก่อนกด เป็นการตัดสินใจที่ไม่ควรต้องเปิดอีกหน้าจอ",
    stat4: "6",
    stat4Label: "Device Mockup",
    reflect1Title: "ออกแบบ Interaction บนแผนที่",
    reflect1Text: "หมุด Bottom Sheet การรวมกลุ่มหมุด และรัศมีการค้นหา ทำงานไม่เหมือนหน้าจอทั่วไป ต้องออกแบบเป็นเรื่องของตัวเอง",
    reflect2Title: "อ่านตลาดก่อนลงมือ",
    reflect2Text: "การไล่ดูของที่มีอยู่แล้ว คือวิธีหาช่องว่างที่ควรออกแบบเข้าไปจริง ๆ แทนที่จะเดาเอา",
    reflect3Title: "งานแนวคิดต้องขายตัวเองได้",
    reflect3Text: "เมื่อไม่มีลูกค้าและไม่มีผู้ใช้จริง Mockup และการนำเสนอคือสิ่งที่แบกข้อโต้แย้งทั้งหมด ซึ่งเป็นทักษะของมันเอง",
    reflect4Title: "เรียนรู้โดเมน",
    reflect4Text: "มาตรฐานหัวชาร์จ ความเร็วในการชาร์จ และรูปแบบราคา ล้วนกำหนดหน้าตาอินเทอร์เฟซ งานนี้ออกแบบจากภายนอกไม่ได้",
    caption4: "แผนที่ — หมุดสถานีที่บอกประเภทหัวชาร์จและกำลังไฟ",
    caption5: "การจอง — ระยะทางและเวลาเดินทาง ก่อนตัดสินใจ",
    caption6: "รายการสถานี — ผู้ให้บริการใกล้เคียง พร้อมประเภทและ kW",
    dataStatus: "real"
  }
};
