/* GENERATED FILE - do not edit by hand.
   Source of truth is content/cases.csv; regenerate with:
     powershell -ExecutionPolicy Bypass -File tools/build-cases.ps1
   Edits made directly here are lost on the next run. */
window.CASE_DATA = {
  en: {
    category: "Product Platform",
    title: "Construction Management Platform",
    summary: "A SaaS platform that puts the tools a construction project needs in one place - documents, schedule, inspections and a project-wide dashboard - so owners, consultants, contractors and subcontractors plan from the same picture.",
    coverAlt: "Construction management platform shown on laptop, tablet and phone",
    role: "UX/UI Designer, Design System Lead",
    timeline: "2022 — ongoing",
    platform: "SaaS - web + mobile",
    tools: "Figma, Design Tokens, Shadcn UI, Tailwind CSS",
    problem1: "The dashboard had been built for executives, and only for them. The data was all there, but an engineer, a contractor or an architect could not pull out the part that applied to their own work - so the people closest to the site were the ones it served worst.",
    problem2: "Nothing could be rearranged: no adding, removing or reordering widgets, so every role opened the same fixed view. Underneath, the Ant Design system it was built on allowed only limited theming, its components were hard to modify, and its tokens were rigid enough to make every handover to development slower than it needed to be.",
    process1: "I audited what Ant Design could and could not be made to do, then rebuilt the design system on Shadcn UI and Tailwind CSS - modular components, tokens we controlled ourselves, and runtime theming through CSS variables. The move ran in five steps: evaluate, decide, restructure, tokenize, and only then build the custom dashboard on top of it.",
    quote: "Short term it cost a rebuild. Long term it bought tokens we control, a handover that lands first time, and theming we can still extend.",
    solution1: "People build their own dashboard - adding, removing and arranging widgets around the work they actually do - and can share a preset as a template for the rest of their team, so a new site does not start from a blank screen. Under it sits the rebuilt system: modular components, controlled tokens, and dynamic theming that carries per-user customisation, brand colour and dark or light mode.",
    caption1: "Custom dashboard - widgets added, removed and arranged per role",
    caption2: "Design tokens and component variants in the rebuilt system",
    caption3: "Dynamic theming: brand colour and dark or light, through CSS variables",
    results1: "Design moved faster and landed more accurately, and the custom dashboard became the feature sales led with - it closed three enterprise accounts: Ananda Development, Gulf Energy and CHPP.",
    stat1: "+60%",
    stat1Label: "UI design speed",
    stat2: "+85%",
    stat2Label: "Dev handoff accuracy",
    stat3: "3",
    stat3Label: "Enterprise accounts closed",
    nextTitle: "EV Charger",
    pageTitle: "Construction Management Platform",
    fwOldLabel: "Ant Design — before",
    fwOld1: "Theme colour only adjustable within fixed limits",
    fwOld2: "UI components hard to modify",
    fwOld3: "Rigid token model",
    fwOld4: "No support for dynamic theming",
    fwOld5: "Slow, error-prone handover to developers",
    fwNewLabel: "Shadcn UI + Tailwind CSS — after",
    fwNew1: "Theme colour system we control end to end",
    fwNew2: "Modular UI components",
    fwNew3: "Design tokens defined by us",
    fwNew4: "Dynamic theming at runtime",
    fwNew5: "Handover developers can read directly",
    fwTradeShort: "A slower first release — every component had to be rebuilt rather than configured.",
    fwTradeLong: "Tokens we own, a handover that lands first time, and theming that can keep being extended instead of worked around.",
    ut1Role: "Project owners",
    ut1Need: "Wanted the project-wide picture, and got it.",
    ut1Ok: "yes",
    ut2Role: "Engineers",
    ut2Need: "Needed detail for their own discipline. The numbers existed, but there was no way to bring just those to the surface.",
    ut2Ok: "no",
    ut3Role: "Contractors and architects",
    ut3Need: "Needed the slice tied to their own scope of work, not a whole-project summary they had to read past.",
    ut3Ok: "no",
    testimonialQuote: "The custom dashboard is what closed our largest enterprise accounts. It answered the thing those clients kept asking for - see the data for my role, arrange it my way - and sales and consulting could finally demonstrate that in the room instead of describing it.",
    testimonialName: "Sales & Consultant team",
    testimonialRole: "Swift Dynamics — enterprise accounts",
    reflect1Title: "Design system architecture",
    reflect1Text: "Building one that stays flexible is an architecture problem, not a styling one. The decisions that mattered were about structure, not appearance.",
    reflect2Title: "Modular components",
    reflect2Text: "Components that can be composed and adjusted individually let one part change without the rest having to move with it.",
    reflect3Title: "Variables and theming at scale",
    reflect3Text: "Managing variables, theme colour and component variants needs a system of its own once the product is large enough. Naming and hierarchy stop being cosmetic.",
    reflect4Title: "Working across three roles at once",
    reflect4Text: "A design system has to hold for UI design, the product owner and the developers at the same time. Anything that only satisfies one of them does not survive contact with the other two."
  },

  th: {
    category: "แพลตฟอร์มผลิตภัณฑ์",
    title: "แพลตฟอร์มบริหารงานก่อสร้าง",
    summary: "แพลตฟอร์ม SaaS ที่รวมเครื่องมือที่งานก่อสร้างต้องใช้ไว้ในที่เดียว - เอกสาร แผนงาน การตรวจสอบ และ Dashboard ภาพรวมโครงการ - ให้เจ้าของโครงการ ที่ปรึกษา ผู้รับเหมา และผู้รับเหมาช่วง วางแผนจากภาพเดียวกัน",
    coverAlt: "แพลตฟอร์มบริหารงานก่อสร้างบนแล็ปท็อป แท็บเล็ต และมือถือ",
    role: "UX/UI Designer, Design System Lead",
    timeline: "2565 — ถึงปัจจุบัน",
    platform: "SaaS - เว็บ + มือถือ",
    tools: "Figma, Design Tokens, Shadcn UI, Tailwind CSS",
    problem1: "Dashboard เดิมถูกสร้างมาเพื่อผู้บริหาร และเพื่อผู้บริหารเท่านั้น ข้อมูลมีครบ แต่วิศวกร ผู้รับเหมา หรือสถาปนิก ดึงส่วนที่ตรงกับงานของตัวเองออกมาดูไม่ได้ คนที่อยู่ใกล้หน้างานที่สุดจึงเป็นกลุ่มที่ระบบตอบโจทย์น้อยที่สุด",
    problem2: "ปรับอะไรไม่ได้เลย เพิ่ม ลบ หรือจัดเรียง Widget เองไม่ได้ ทุกบทบาทจึงเปิดมาเจอหน้าจอชุดเดียวกันหมด ลึกลงไปกว่านั้น Design System เดิมที่วางอยู่บน Ant Design ปรับ Theme ได้จำกัด แก้ Component ได้ยาก และ Token แข็งเกินกว่าจะส่งงานให้ Developer ได้เร็วอย่างที่ควรเป็น",
    process1: "ผมประเมินว่า Ant Design ทำอะไรได้และดัดให้ทำอะไรไม่ได้บ้าง แล้วรื้อ Design System ใหม่บน Shadcn UI และ Tailwind CSS - Component แบบ Modular, Token ที่เราคุมเองได้ และ Runtime Theming ผ่าน CSS Variables ทั้งหมดเดินเป็นห้าขั้น: ประเมิน ตัดสินใจ วางโครง Tokenize แล้วจึงต่อยอดเป็น Custom Dashboard",
    quote: "ระยะสั้นแลกด้วยการรื้อใหม่ ระยะยาวได้ Token ที่คุมเองได้ การส่งงานที่จบในรอบเดียว และ Theme ที่ยังต่อยอดได้",
    solution1: "ผู้ใช้ประกอบ Dashboard ของตัวเองได้ - เพิ่ม ลบ จัดเรียง Widget รอบงานที่ทำจริง และแชร์ Preset เป็นเทมเพลตให้คนอื่นในทีมได้ ไซต์งานใหม่จึงไม่ต้องเริ่มจากหน้าจอเปล่า ข้างใต้คือระบบที่รื้อใหม่ทั้งหมด: Component แบบ Modular, Token ที่ควบคุมได้ และ Dynamic Theming ที่รองรับการปรับแต่งรายคน สีแบรนด์ และโหมดสว่างหรือมืด",
    caption1: "Custom Dashboard - เพิ่ม ลบ และจัดเรียง Widget ตามบทบาท",
    caption2: "Design Token และ Component Variant ในระบบที่รื้อใหม่",
    caption3: "Dynamic Theming: สีแบรนด์และโหมดสว่าง/มืด ผ่าน CSS Variables",
    results1: "งานออกแบบเดินเร็วขึ้นและส่งงานได้แม่นขึ้น ส่วน Custom Dashboard กลายเป็นฟีเจอร์ที่ทีมขายใช้นำเสนอเป็นตัวชูโรง และปิดลูกค้า Enterprise ได้สามราย: Ananda Development, Gulf Energy และ CHPP",
    stat1: "+60%",
    stat1Label: "ความเร็วในการออกแบบ UI",
    stat2: "+85%",
    stat2Label: "ความแม่นยำในการส่งงานให้ Dev",
    stat3: "3",
    stat3Label: "ลูกค้า Enterprise ที่ปิดได้",
    nextTitle: "แอปชาร์จรถ EV",
    pageTitle: "Construction Management Platform",
    fwOldLabel: "Ant Design — เดิม",
    fwOld1: "ปรับ Theme Color ได้จำกัด",
    fwOld2: "แก้ไข UI Component ได้ยาก",
    fwOld3: "ระบบ Token ไม่ยืดหยุ่น",
    fwOld4: "ไม่รองรับ Dynamic Theme",
    fwOld5: "สื่อสารกับ Developer ได้ยาก",
    fwNewLabel: "Shadcn UI + Tailwind CSS — ใหม่",
    fwNew1: "ระบบ Theme Color ที่ยืดหยุ่นสูง",
    fwNew2: "UI Component แบบ Modular",
    fwNew3: "Design Token ที่ควบคุมเองได้",
    fwNew4: "รองรับ Dynamic Theme",
    fwNew5: "สื่อสารกับ Dev ได้ชัดเจน",
    fwTradeShort: "ออกช้าลงในรอบแรก เพราะต้องรื้อสร้าง Component ใหม่ทั้งหมด ไม่ใช่แค่ตั้งค่า",
    fwTradeLong: "ได้ Token ที่เป็นของเราเอง ส่งงานจบในรอบเดียว และ Theme ที่ต่อยอดต่อได้เรื่อย ๆ แทนที่จะต้องหาทางเลี่ยง",
    ut1Role: "ผู้บริหารโครงการ",
    ut1Need: "ต้องการภาพรวมทั้งโครงการ และได้ตามนั้น",
    ut1Ok: "yes",
    ut2Role: "วิศวกร",
    ut2Need: "ต้องการข้อมูลเชิงลึกเฉพาะสายงานของตัวเอง ตัวเลขมีอยู่ แต่ไม่มีทางดึงเฉพาะส่วนนั้นขึ้นมาดูได้",
    ut2Ok: "no",
    ut3Role: "ผู้รับเหมาและสถาปนิก",
    ut3Need: "ต้องการเฉพาะส่วนที่ผูกกับขอบเขตงานของตัวเอง ไม่ใช่ภาพรวมทั้งโครงการที่ต้องไล่อ่านผ่านไป",
    ut3Ok: "no",
    testimonialQuote: "ฟีเจอร์ Custom Dashboard คือสิ่งที่ทำให้ปิดดีลลูกค้า Enterprise รายใหญ่ได้ เพราะมันตอบสิ่งที่ลูกค้ากลุ่มนั้นถามมาตลอด - ขอดูข้อมูลตามบทบาทของตัวเอง และจัดวางเองได้ - ทีม Sales และ Consultant จึงสาธิตให้ดูได้จริงในห้องประชุม แทนที่จะได้แค่เล่าให้ฟัง",
    testimonialName: "ทีม Sales & Consultant",
    testimonialRole: "Swift Dynamics — ลูกค้ากลุ่ม Enterprise",
    reflect1Title: "สถาปัตยกรรมของ Design System",
    reflect1Text: "การสร้าง Design System ที่ยังยืดหยุ่นอยู่ได้ เป็นเรื่องของสถาปัตยกรรม ไม่ใช่การจัดสไตล์ การตัดสินใจที่สำคัญจริง ๆ อยู่ที่โครงสร้าง ไม่ใช่หน้าตา",
    reflect2Title: "Component แบบ Modular",
    reflect2Text: "Component ที่ประกอบและปรับแยกส่วนได้ ทำให้แก้ตรงหนึ่งได้โดยที่ส่วนอื่นไม่ต้องขยับตาม",
    reflect3Title: "การจัดการ Variables และ Theme เมื่อระบบใหญ่ขึ้น",
    reflect3Text: "พอผลิตภัณฑ์ใหญ่ถึงจุดหนึ่ง การจัดการ Variables, Theme Color และ Component Variant ต้องมีระบบของตัวเอง การตั้งชื่อและลำดับชั้นเลิกเป็นเรื่องความสวยงามแล้ว",
    reflect4Title: "การทำงานกับสามฝ่ายพร้อมกัน",
    reflect4Text: "Design System ต้องใช้ได้พร้อมกันทั้งฝั่ง UI Design, Product Owner และ Developer สิ่งที่ตอบโจทย์แค่ฝ่ายเดียวจะอยู่ไม่รอดเมื่อเจออีกสองฝ่าย"
  }
};
