/* GENERATED FILE - do not edit by hand.
   Source of truth is content/cases.csv; regenerate with:
     powershell -ExecutionPolicy Bypass -File tools/build-cases.ps1
   Edits made directly here are lost on the next run. */
window.CASE_DATA = {
  en: {
    category: "Mobile Application",
    title: "DR.in for Doctor",
    summary: "A digital health platform putting teleconsultation and e-prescription in reach online, at minimal cost.",
    coverAlt: "DR.in for Doctor app screens shown on three phones",
    role: "UI Designer (Internship)",
    timeline: "2021–2022 — 5 months",
    platform: "Mobile — iOS and Android",
    tools: "Figma, Figma Prototype, Design System",
    problem1: "Medical data is dense by nature, and a prescription is not a form you can afford to get wrong.",
    problem2: "",
    process1: "The brief and wireframes came from the senior UX team, and the first job was understanding the user flow and the business logic behind them before drawing anything. The hardest part was the domain itself: I had to learn how prescribing actually works before the screens could be right rather than merely tidy.",
    quote: "In a medical interface, accuracy and safety come before aesthetics — a screen that looks calm but reads wrong is the worse outcome.",
    solution1: "The visual direction had to read as trustworthy without turning clinical. Complex data was grouped so a prescription could be checked at a glance rather than parsed, and every foundational screen — Login and Settings included — was held to the same rules as the core flow.",
    caption1: "Login — welcome and sign-in, carrying the deep purple branding",
    caption2: "Dashboard — the day's booking list, each with its status colour",
    caption3: "Calendar — the month at a glance, with each day's patients beneath",
    results1: "Every screen shipped within the sprint timeline, built entirely from the shared component library — and reviewing an interactive prototype before development began kept requirements from drifting once the build was underway.",
    stat1: "20+",
    stat1Label: "Screens designed",
    stat2: "5",
    stat2Label: "Core flows delivered",
    stat3: "50+",
    stat3Label: "Components in the library",
    nextTitle: "Custom IoT monitoring dashboards",
    pageTitle: "DR.in for Doctor",
    team: "Senior UX/UI Designers · Product Manager · Developers",
    contextText: "A teleconsultation and e-prescription app for healthcare professionals. Working alongside senior UX/UI designers, I turned requirements into working screens — from the e-prescription core flow through to the foundational ones, Login and Settings included. Its users are doctors, medical staff and patients.",
    prob1Title: "The Problem",
    prob1Text: "Medical data and e-prescription workflows are inherently dense and complex. The challenge was displaying that information architecture without overwhelming the people using it — healthcare professionals and patients alike.",
    prob2Title: "",
    prob2Text: "",
    prob3Title: "",
    prob3Text: "",
    goalTitle: "The Goal",
    goalText: "Translate the UX team's requirements into a clean, modern and genuinely intuitive interface — cutting cognitive load so the experience stays frictionless and easy to read.",
    ps1Title: "Requirement Review",
    ps1Text: "Take the brief and wireframes from senior UX; understand the flow and the business logic",
    ps2Title: "UI Research",
    ps2Text: "Gather references from established medical apps and set the visual direction",
    ps3Title: "UI Design",
    ps3Text: "Draw the high-fidelity screens against the agreed component system",
    ps4Title: "Prototype & Review",
    ps4Text: "Build an interactive prototype to review with the PM and stakeholders",
    ps5Title: "Dev Handoff",
    ps5Text: "Hand over specs, assets and component documentation",
    dec1Title: "Purple-blue as the primary",
    dec1Why: "Reads as medically trustworthy without going cold or severe, which keeps it approachable for patients as well as staff.",
    dec2Title: "Large, plainly legible type",
    dec2Why: "Doctors read this mid-consultation, often in poor light. It has to be legible at a glance, not on inspection.",
    dec3Title: "Card-based layout",
    dec3Why: "Splits patient information into visible categories, so the eye can skip to the section it needs instead of scanning a wall.",
    dec4Title: "Colour-coded status tags",
    dec4Why: "Green, amber and red separate appointment states at a glance, which matters when time per patient is short.",
    stat4: "100%",
    stat4Label: "Screens on the shared system",
    reflect1Title: "Healthcare UX",
    reflect1Text: "In a medical domain, accuracy and safety outrank aesthetics. A screen that looks good and reads ambiguously has failed.",
    reflect2Title: "Visual decisions with a reason",
    reflect2Text: "Colour, type size and spacing are not taste here — each one changes how quickly a doctor can read the screen correctly.",
    reflect3Title: "Working inside a design team",
    reflect3Text: "The real process end to end — taking a brief, receiving review, iterating quickly, and holding consistency to a guideline rather than to preference.",
    reflect4Title: "Component discipline",
    reflect4Text: "Using the library strictly, without one-off designs, is what makes a handover clean and lets development move.",
    caption4: "Drug detail — name, dose, quantity, directions and indications",
    caption5: "Patient information — the record form, grouped by category",
    caption6: "Settings — profile, licence and lab, kept to the same rules",
    caption7: "E-prescription — the core flow, from selecting a drug to confirming the order",
    dataStatus: "real"
  },

  th: {
    category: "แอปพลิเคชันมือถือ",
    title: "DR.in for Doctor",
    summary: "แพลตฟอร์มสุขภาพดิจิทัลที่ให้บริการปรึกษาแพทย์และสั่งยาออนไลน์ เข้าถึงได้ครบและค่าใช้จ่ายต่ำ",
    coverAlt: "หน้าจอแอป DR.in for Doctor บนโทรศัพท์สามเครื่อง",
    role: "UI Designer (ฝึกงาน)",
    timeline: "2564–2565 — 5 เดือน",
    platform: "มือถือ — iOS และ Android",
    tools: "Figma, Figma Prototype, Design System",
    problem1: "ข้อมูลทางการแพทย์ซับซ้อนโดยธรรมชาติ และใบสั่งยาไม่ใช่ฟอร์มที่กรอกผิดได้",
    problem2: "",
    process1: "Brief และ Wireframe มาจากทีม Senior UX งานแรกคือทำความเข้าใจ User Flow และ Business Logic เบื้องหลังก่อนจะเริ่มออกแบบ ส่วนที่ยากที่สุดคือตัวโดเมนเอง ผมต้องเรียนรู้ว่าการสั่งยาจริงทำงานอย่างไร ก่อนที่หน้าจอจะถูกต้อง ไม่ใช่แค่ดูเรียบร้อย",
    quote: "ในงานออกแบบทางการแพทย์ ความถูกต้องและความปลอดภัยมาก่อนความสวยงาม หน้าจอที่ดูสงบแต่อ่านแล้วเข้าใจผิด คือผลลัพธ์ที่แย่กว่า",
    solution1: "Visual Direction ต้องให้ความรู้สึกน่าเชื่อถือโดยไม่แข็งจนเกินไป ข้อมูลที่ซับซ้อนถูกจัดกลุ่มให้ตรวจใบสั่งยาได้ในสายตาเดียว ไม่ต้องไล่อ่าน และหน้าจอพื้นฐานทุกหน้า รวมถึง Login และ Settings ยึดกฎเดียวกับ Core Flow",
    caption1: "Login — หน้าต้อนรับและเข้าสู่ระบบ ใช้โทนม่วงเข้มของแบรนด์",
    caption2: "Dashboard — รายการนัดหมายของวัน พร้อมสีบอกสถานะ",
    caption3: "ปฏิทิน — ดูทั้งเดือนในครั้งเดียว พร้อมรายชื่อผู้ป่วยของแต่ละวัน",
    results1: "ส่งมอบครบทุกหน้าจอตามกรอบเวลา Sprint และสร้างจาก Component Library ชุดเดียวกันทั้งหมด ส่วนการรีวิว Interactive Prototype ก่อนเริ่มพัฒนา ช่วยไม่ให้ Requirement เคลื่อนระหว่างทาง",
    stat1: "20+",
    stat1Label: "หน้าจอที่ออกแบบ",
    stat2: "5",
    stat2Label: "Core Flow ที่ส่งมอบ",
    stat3: "50+",
    stat3Label: "Component ใน Library",
    nextTitle: "แดชบอร์ดตรวจสอบ IoT แบบสั่งทำ",
    pageTitle: "DR.in for Doctor",
    team: "Senior UX/UI Designers · Product Manager · Developers",
    contextText: "แอปปรึกษาแพทย์และสั่งยาออนไลน์สำหรับบุคลากรทางการแพทย์ ผมทำงานร่วมกับ Senior UX/UI Designer แปลง Requirement ให้เป็นหน้าจอที่ใช้งานได้จริง ตั้งแต่ Core Flow ของการสั่งยา ไปจนถึงหน้าจอพื้นฐานอย่าง Login และ Settings กลุ่มผู้ใช้คือแพทย์ บุคลากรทางการแพทย์ และผู้ป่วย",
    prob1Title: "โจทย์",
    prob1Text: "ข้อมูลทางการแพทย์และขั้นตอนการสั่งยาออนไลน์ซับซ้อนในตัวเอง ความท้าทายคือจะแสดงโครงสร้างข้อมูลจำนวนมากนี้อย่างไรโดยไม่ทำให้ผู้ใช้ทั้งบุคลากรทางการแพทย์และผู้ป่วยรู้สึกล้น",
    prob2Title: "",
    prob2Text: "",
    prob3Title: "",
    prob3Text: "",
    goalTitle: "เป้าหมาย",
    goalText: "แปลง Requirement จากทีม UX ให้เป็นอินเทอร์เฟซที่สะอาด ทันสมัย และเข้าใจง่ายจริง ลด Cognitive Load ให้การใช้งานลื่นไหลและอ่านสบาย",
    ps1Title: "รับ Requirement",
    ps1Text: "รับ Brief และ Wireframe จากทีม Senior UX เข้าใจ User Flow และ Business Logic",
    ps2Title: "ค้นคว้า UI",
    ps2Text: "รวบรวม UI Reference จากแอปทางการแพทย์ชั้นนำ กำหนด Visual Direction",
    ps3Title: "ออกแบบ UI",
    ps3Text: "ออกแบบ High-fidelity Screen ตาม Component System ที่กำหนด",
    ps4Title: "Prototype และรีวิว",
    ps4Text: "สร้าง Interactive Prototype เพื่อรีวิวกับ PM และ Stakeholder",
    ps5Title: "ส่งมอบให้ Dev",
    ps5Text: "ส่งมอบ Design Spec, Asset และเอกสาร Component",
    dec1Title: "ใช้ม่วง-น้ำเงินเป็นสีหลัก",
    dec1Why: "สื่อถึงความน่าเชื่อถือทางการแพทย์ แต่ไม่แข็งหรือเย็นชาเกินไป ยังเข้าถึงง่ายทั้งกับผู้ป่วยและเจ้าหน้าที่",
    dec2Title: "ตัวอักษรขนาดใหญ่ อ่านง่าย",
    dec2Why: "แพทย์อ่านระหว่างตรวจคนไข้ และมักอยู่ในสภาพแสงไม่ดี จึงต้องอ่านออกในพริบตา ไม่ใช่ต้องเพ่ง",
    dec3Title: "เลย์เอาต์แบบการ์ด",
    dec3Why: "แบ่งข้อมูลผู้ป่วยเป็นหมวดที่มองเห็นได้ สายตาจึงข้ามไปยังส่วนที่ต้องการได้เลย แทนที่จะกวาดทั้งหน้า",
    dec4Title: "แท็กสถานะแยกด้วยสี",
    dec4Why: "เขียว เหลือง แดง แยกสถานะนัดหมายให้เห็นในครั้งเดียว ซึ่งสำคัญเมื่อเวลาต่อคนไข้มีจำกัด",
    stat4: "100%",
    stat4Label: "หน้าจอที่ใช้ระบบร่วมกัน",
    reflect1Title: "เข้าใจ Healthcare UX",
    reflect1Text: "ในโดเมนทางการแพทย์ ความถูกต้องและความปลอดภัยสำคัญกว่าความสวยงาม หน้าจอที่ดูดีแต่อ่านแล้วกำกวม คือหน้าจอที่ล้มเหลว",
    reflect2Title: "Visual Design ที่มีเหตุผลรองรับ",
    reflect2Text: "สี ขนาดตัวอักษร และระยะห่าง ไม่ใช่เรื่องรสนิยมในงานนี้ แต่ละอย่างเปลี่ยนความเร็วที่แพทย์อ่านหน้าจอได้ถูกต้อง",
    reflect3Title: "ทำงานในทีม Design จริง",
    reflect3Text: "ได้เห็นกระบวนการจริงตั้งแต่ต้นจนจบ รับ Brief รับ Feedback ปรับแก้อย่างรวดเร็ว และรักษาความสม่ำเสมอตาม Guideline ไม่ใช่ตามความชอบ",
    reflect4Title: "วินัยเรื่อง Component",
    reflect4Text: "การใช้ Component Library อย่างเคร่งครัด ไม่สร้างงานเฉพาะกิจ คือสิ่งที่ทำให้การส่งมอบสะอาดและทีม Dev เดินงานต่อได้",
    caption4: "รายละเอียดยา — ชื่อยา ขนาด จำนวน วิธีใช้ และข้อบ่งใช้",
    caption5: "ข้อมูลผู้ป่วย — ฟอร์มบันทึกข้อมูล จัดกลุ่มตามหมวด",
    caption6: "ตั้งค่า — ข้อมูลส่วนตัว ใบอนุญาต และแลป ยึดกฎเดียวกัน",
    caption7: "สั่งยาออนไลน์ — Core Flow ตั้งแต่เลือกยาจนยืนยันใบสั่ง",
    dataStatus: "real"
  }
};
